FROM python:3.8-slim-buster AS build

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir pyinstaller

COPY . .

RUN pyinstaller --onefile --name CoinCorrView main.py
RUN mv dist/CoinCorrView dist/CoinCorrView-arm

FROM scratch AS export
COPY --from=build /app/dist/CoinCorrView-arm /
